//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.28 at 02:13:48 PM CET 
//


package it.rnsinfo;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for placeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="placeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifiedEntity" type="{http://www.rnsInfo.it}identifiedEntityType"/>
 *         &lt;element name="isConnectedTo" type="{http://www.rnsInfo.it}idType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="roadSegment" type="{http://www.rnsInfo.it}roadSegmentType"/>
 *           &lt;element name="parkingArea" type="{http://www.rnsInfo.it}parkingAreaType"/>
 *           &lt;element name="gate" type="{http://www.rnsInfo.it}gateType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="capacity" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "placeType", propOrder = {
    "identifiedEntity",
    "isConnectedTo",
    "roadSegment",
    "parkingArea",
    "gate"
})
public class PlaceType {

    @XmlElement(required = true)
    protected IdentifiedEntityType identifiedEntity;
    protected List<String> isConnectedTo;
    protected RoadSegmentType roadSegment;
    protected ParkingAreaType parkingArea;
    protected String gate;
    @XmlAttribute(name = "capacity", required = true)
    protected BigInteger capacity;

    /**
     * Gets the value of the identifiedEntity property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifiedEntityType }
     *     
     */
    public IdentifiedEntityType getIdentifiedEntity() {
        return identifiedEntity;
    }

    /**
     * Sets the value of the identifiedEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifiedEntityType }
     *     
     */
    public void setIdentifiedEntity(IdentifiedEntityType value) {
        this.identifiedEntity = value;
    }

    /**
     * Gets the value of the isConnectedTo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isConnectedTo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsConnectedTo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIsConnectedTo() {
        if (isConnectedTo == null) {
            isConnectedTo = new ArrayList<String>();
        }
        return this.isConnectedTo;
    }

    /**
     * Gets the value of the roadSegment property.
     * 
     * @return
     *     possible object is
     *     {@link RoadSegmentType }
     *     
     */
    public RoadSegmentType getRoadSegment() {
        return roadSegment;
    }

    /**
     * Sets the value of the roadSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoadSegmentType }
     *     
     */
    public void setRoadSegment(RoadSegmentType value) {
        this.roadSegment = value;
    }

    /**
     * Gets the value of the parkingArea property.
     * 
     * @return
     *     possible object is
     *     {@link ParkingAreaType }
     *     
     */
    public ParkingAreaType getParkingArea() {
        return parkingArea;
    }

    /**
     * Sets the value of the parkingArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParkingAreaType }
     *     
     */
    public void setParkingArea(ParkingAreaType value) {
        this.parkingArea = value;
    }

    /**
     * Gets the value of the gate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGate() {
        return gate;
    }

    /**
     * Sets the value of the gate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGate(String value) {
        this.gate = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCapacity(BigInteger value) {
        this.capacity = value;
    }

}
