//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.28 at 02:13:48 PM CET 
//


package it.rnsinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for vehicleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vehicleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifiedEntity" type="{http://www.rnsInfo.it}identifiedEntityType"/>
 *         &lt;element name="origin" type="{http://www.rnsInfo.it}idType"/>
 *         &lt;element name="destination" type="{http://www.rnsInfo.it}idType"/>
 *         &lt;element name="position" type="{http://www.rnsInfo.it}idType"/>
 *         &lt;element name="entryTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *       &lt;attribute name="vehicleType" use="required" type="{http://www.rnsInfo.it}enumVehicleType" />
 *       &lt;attribute name="vehicleState" use="required" type="{http://www.rnsInfo.it}enumVehicleState" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vehicleType", propOrder = {
    "identifiedEntity",
    "origin",
    "destination",
    "position",
    "entryTime"
})
public class VehicleType {

    @XmlElement(required = true)
    protected IdentifiedEntityType identifiedEntity;
    @XmlElement(required = true)
    protected String origin;
    @XmlElement(required = true)
    protected String destination;
    @XmlElement(required = true)
    protected String position;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar entryTime;
    @XmlAttribute(name = "vehicleType", required = true)
    protected EnumVehicleType vehicleType;
    @XmlAttribute(name = "vehicleState", required = true)
    protected EnumVehicleState vehicleState;

    /**
     * Gets the value of the identifiedEntity property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifiedEntityType }
     *     
     */
    public IdentifiedEntityType getIdentifiedEntity() {
        return identifiedEntity;
    }

    /**
     * Sets the value of the identifiedEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifiedEntityType }
     *     
     */
    public void setIdentifiedEntity(IdentifiedEntityType value) {
        this.identifiedEntity = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosition(String value) {
        this.position = value;
    }

    /**
     * Gets the value of the entryTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEntryTime() {
        return entryTime;
    }

    /**
     * Sets the value of the entryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEntryTime(XMLGregorianCalendar value) {
        this.entryTime = value;
    }

    /**
     * Gets the value of the vehicleType property.
     * 
     * @return
     *     possible object is
     *     {@link EnumVehicleType }
     *     
     */
    public EnumVehicleType getVehicleType() {
        return vehicleType;
    }

    /**
     * Sets the value of the vehicleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumVehicleType }
     *     
     */
    public void setVehicleType(EnumVehicleType value) {
        this.vehicleType = value;
    }

    /**
     * Gets the value of the vehicleState property.
     * 
     * @return
     *     possible object is
     *     {@link EnumVehicleState }
     *     
     */
    public EnumVehicleState getVehicleState() {
        return vehicleState;
    }

    /**
     * Sets the value of the vehicleState property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumVehicleState }
     *     
     */
    public void setVehicleState(EnumVehicleState value) {
        this.vehicleState = value;
    }

}
